# Note: Dracula is dark only theme, disable the switcher, and set the default to dark
appearance:
  default: dark
  switcher: false

# Dracula theme, see https://draculatheme.com/
theme:
  colorPalettes:
    default:
      - "#bd93f9"  # Purple
      - "#8be9fd"  # Cyan
      - "#ff79c6"  # Pink
      - "#50fa7b"  # Green
      - "#ffb86c"  # Orange
      - "#ff5555"  # Red
      - "#f1fa8c"  # Yellow
      - "#6272a4"  # Comment
      
  colorScales:
    default:
      - "#bd93f9"  # Purple
      - "#ff79c6" # Pink
      
  colors:
    primary:
      light: "#bd93f9"  # Purple
      dark: "#bd93f9"  # Purple
    accent:
      light: "#ff79c6"  # Pink
      dark: "#ff79c6"  # Pink
    base:
      light: "#f8f8f2"  # Foreground
      dark: "#282a36"  # Background
    info:
      light: "#8be9fd"  # Cyan
      dark: "#8be9fd"  # Cyan
    warning:
      light: "#ffb86c"  # Orange
      dark: "#ffb86c"  # Orange
    negative:
      light: "#ff5555"  # Red
      dark: "#ff5555"  # Red
    positive:
      light: "#50fa7b"  # Green
      dark: "#50fa7b"  # Green