# Desert theme
theme:
  colorPalettes:
    default:
      - "#8b4513"  # Saddle Brown
      - "#a0522d"  # Sienna 
      - "#d2691e"  # Chocolate
      - "#cd853f"  # Peru
      - "#d2b48c"  # Tan
      - "#deb887"  # Burlywood
      - "#f4a460"  # Sandy Brown
      - "#f5deb3"  # Wheat
      - "#ffdead"  # Navajo White
      - "#ffe4c4"  # Bisque
  colors:
    primary:
      light: "#8b4513"  # Saddle Brown
      dark: "#deb887"  # Burlywood
    accent:
      light: "#cd853f"  # Peru
      dark: "#8b4513"  # Saddle Brown
    base:
      light: "#fff5ee"  # Seashell
      dark: "#1a1410"  # Night Desert
    info:
      light: "#cd3f3f"  # Salmon
      dark: "#ffe4c4"  # Bisque
